version: "3.8"
name: countfy
services:

  database:
    container_name: Countfy-Postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: countfydb
    restart: unless-stopped

  postgres_admin:
    restart: always
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin

  backend:
    container_name: Countfy-Backend
    build:
      context: ./backend
      target: development
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=pguser
      - DB_PASSWORD=pgpassword
      - DB_NAME=countfydb
      - NODE_ENV=development
      - JWT_SECRET=secret
      - JWT_EXPIRATION_TIME=90d
      - SALT_ROUNDS=10
    depends_on:
      - database
    command: npm run start:dev

  frontend:
    container_name: Countfy-Frontend
    build:
      context: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/var/www/html
    ports:
      - 8002:80
    depends_on:
      - backend

volumes:
  pg-data:

